baseURL = "https://example.org"
languageCode = "zh-cn"
title = "Hugo Canoe Theme"


theme = "canoe"

# I prefer to yaml
metaDataFormat = "yaml"


# if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
hasCJKLanguage = true



[params]
  author = "Kevin Tan"
  subtitle = "Tempora mutantur, nos et mutamur in illis ..."
  copyright = "Copyleft@Kevin Tan"

  # 用户头像地址, user avatar's url
  logo = "/img/avatar.jpg"
  
  # 首页横幅的背景链接, home banner's background url.
  splash_bg = "/img/bg.jpg"

  # 是否使用一言, if using hitokoto(dynamic moto in splash screen)
  hitokoto = true

  # 是否使用Canvas动态背景, if using canvas dynamic background (nest.js)
  nest_bg = false

  # 是否使用动态加载效果, if using fade effect while loading (scroll-reveal.js)
  reveal_effect = true
  
# comment settings, support 'valine' and 'disqus'.
# more about 'valine', ref: http://valine.js.org/
[params.comment]
  type = "valine" # or 'disqus'

[params.comment.valine]
  id = "< the appId >"
  key = "< the appKey >"
  placeholder = "< placeholder >"
  avatar = "retro"

[params.comment.disqus]
  shortname = '< short name >'


# Main menu
[[menu.main]]
    name = "Home"
    # associated with displaying order.
    weight = 1 
    url = "/"

[[menu.main]]
    name = "Archive"
    weight = 2
    url = "/archive/"
    
[[menu.main]]
    name = "About"
    weight = 6
    url = "/about/"



# 文章归类 Taxonomy
[[menu.taxonomy]]
  name = "Tag"
  identifier="tags"

[[menu.taxonomy]]
  name = "Category"
  identifier="categories"

#  友情链接 Your Friend's blog links
[[menu.friend]]
  name = "Frantic1048"
  url = "https://frantic1048.logdown.com/"

[[menu.friend]]
  name = "HclMaster"
  url = "https://hclmaster.github.io/"

[[menu.friend]]
  name = "WANG Hsü-Tung"
  url = "https://whst.github.io/"


# 社交账号 Social Network
[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-github'><use xlink:href='#svg-icons-github'></use></svg>"
  name = "Github"
  url = "https://github.com/stkevintan"

[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-twitter'><use xlink:href='#svg-icons-twitter'></use></svg>"
  name = "Twitter"
  url = "https://twitter.com/kevinsfork"

[[menu.social]]
  pre = "<svg class='svg-icons svg-icons-sina-weibo'><use xlink:href='#svg-icons-sina-weibo'></use></svg>"
  name = "Weibo"
  url = "http://weibo.com/kevinclasky"
